---
- name: Deploy dnscrypt-proxy.toml
  ansible.builtin.template:
    src:   "dnscrypt-proxy.toml.j2"
    dest:  "{{ dnscrypt_proxy_path }}/dnscrypt-proxy.toml"
    mode:  0755
  become: true
  register: dnscrypt_proxy_config

- name: Docker pull elgeeko/dnscrypt-proxy:{{ dnscrypt_proxy_docker_tag }}
  community.general.docker_image:
    name: elgeeko/dnscrypt-proxy:{{ dnscrypt_proxy_docker_tag }}
    source: pull
    force_source: true

- name: Create docker volume dnscrypt-proxy-cache
  community.docker.docker_volume:
    name: dnscrypt-proxy-cache

- name: Start dnscrypt-proxy docker container
  community.general.docker_container:
    name: dnscrypt-proxy
    image: elgeeko/dnscrypt-proxy:{{ dnscrypt_proxy_docker_tag }}
    state: started
    comparisons:
      image: strict
      env: strict
      volumes: strict
    container_default_behavior: no_defaults
    command_handling: correct
    restart: "{{ dnscrypt_proxy_config.changed }}"
    restart_policy: unless-stopped
    volumes:
      - "{{ dnscrypt_proxy_path }}/dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml:ro"
      - dnscrypt-proxy-cache:/var/cache/dnscrypt-proxy
    ports:
      - "{{ dnscrypt_proxy_port }}:5053/tcp"
      - "{{ dnscrypt_proxy_port }}:5053/udp"
      - "[::0]:{{ dnscrypt_proxy_port }}:5053/tcp"
      - "[::0]:{{ dnscrypt_proxy_port }}:5053/udp"
    dns_servers:
      - "9.9.9.9"
      - "149.112.112.112"
      - "2620:fe::fe"
      - "2620:fe::9"
