---
- name: apt update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # 1 hr
    force_apt_get: true
  become: true

- name: Configure filesystem
  ansible.builtin.import_tasks: filesystem.yml

- name: Configure dnscrypt-proxy
  ansible.builtin.import_tasks: dnscrypt-proxy.yml
